project:
  type: website
  output-dir: docs

website:
  title: "Aliyan Mousa Portfolio"
  navbar:
    title: "Aliyan Mousa"
    left:
      - href: index.qmd
        text: Home
      - href: coursework.qmd
        text: Coursework
      - href: projects.qmd
        text: Projects
      - text: Data Science
        menu:
          - href: data-viz.qmd
            text: Data Visualization
          - href: advanced-viz.qmd
            text: Advanced Visualization
          - href: data-wrangling.qmd
            text: Data Wrangling
          - href: r-programming.qmd
            text: R Programming
      - href: marketing.qmd
        text: Marketing
      - href: certifications.qmd
        text: Certifications
      - href: analytics.qmd
        text: Analytics
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
    right:
      - icon: envelope
        href: mailto:mousa.aliyan@outlook.com
      - icon: linkedin
        href: https://www.linkedin.com/in/mousa-aliyan-553488356
      - icon: github
        href: https://github.com/aliyanmousa

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false

editor: visual